# -*- coding: utf-8 -*-
"""Lab2: Text Preprocessing Pipeline.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tFOPe1zO83LQ3OO0C2D7Ln1xm1PucY20

Setup: Install and Import Libraries
"""

# Install required libraries (uncomment if needed)
# !pip install nltk spacy
!python -m spacy download en_core_web_sm

from nltk.tokenize import word_tokenize, sent_tokenize
import spacy
nlp = spacy.load('en_core_web_sm')

"""Part 1: Tokenization

# TODO: Exercise 1.1
"""

import nltk
nltk.download('punkt_tab')

# TODO: Exercise 1.1
# Tokenize the following text into words using NLTK
# Count how many tokens are produced

text = "Dr. Smith's patients can't understand why they're feeling unwell. Is it the flu?"

tokens = word_tokenize(text)
num_tokens = len(tokens)

print("Tokens:", tokens)
print("Number of tokens:", num_tokens)

assert num_tokens == 18, f"Expected 18 tokens, got {num_tokens}"

"""# TODO: Exercise 1.2"""

# Use spaCy to tokenize the text and extract only:
# 1. Tokens that are NOT punctuation
# 2. Tokens that are NOT spaces
# Hint: use token.is_punct and token.is_space

text = "The quick, brown fox jumps over the lazy dog! Isn't it amazing?"

doc = nlp(text)

clean_tokens = [token.text for token in doc if not token.is_punct and not token.is_space]

print("Clean tokens:", clean_tokens)
assert len(clean_tokens) == 13, f"Expected 13 tokens, got {len(clean_tokens)}"

"""# TODO: Exercise 1.3"""

from nltk.tokenize import RegexpTokenizer

# Create a RegexpTokenizer that extracts only alphabetic words (no numbers, no punctuation)

text = "I have 3 cats and 2 dogs! Their names are Max123 and Bella."

alpha_tokenizer = RegexpTokenizer(r"[a-zA-Z]+")
alpha_tokens = alpha_tokenizer.tokenize(text)

print("Alphabetic tokens:", alpha_tokens)

assert alpha_tokens == ['I', 'have', 'cats', 'and', 'dogs', 'Their', 'names', 'are', 'Max', 'and', 'Bella'], "Check your pattern!"

"""Part 2: Stemming and Lemmatization

# TODO: Exercise 2.1
"""

from nltk.stem import PorterStemmer

# Apply Porter stemming to all words in the sentence
# Return the stemmed tokens as a list

# Initialize the Porter Stemmer
porter = PorterStemmer()

sentence = "The cats are running and jumping over the sleeping dogs"

# Step 1: Tokenize (use word_tokenize)
tokens = word_tokenize(sentence)

# Step 2: Apply stemming to each token
stemmed_tokens = [porter.stem(token) for token in tokens]

print("Original:", tokens)
print("Stemmed:", stemmed_tokens)

assert stemmed_tokens == ['the', 'cat', 'are', 'run', 'and', 'jump', 'over', 'the', 'sleep', 'dog'], "Check your stemming!"

"""# TODO: Exercise 2.2"""

from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')

# Lemmatize the following words using the correct POS tag

lemmatizer = WordNetLemmatizer()

# Format: (word, pos_tag)
words_with_pos = [
    ("flying", "v"),
    ("happily", "r"),
    ("worse", "a"),
    ("mice", "n"),
    ("are", "v"),
]

print("Lemmatization results:")
for word, pos in words_with_pos:
    lemma = lemmatizer.lemmatize(word, pos=pos)
    print(f"{word:12} ({pos}) -> {lemma}")

# Verify your answers
expected = ['fly', 'happily', 'bad', 'mouse', 'be']
results = [lemmatizer.lemmatize(w, pos=p) for w, p in words_with_pos]

assert results == expected, f"Expected {expected}, got {results}"

"""# TODO: Exercise 2.3"""

# Use spaCy to extract the lemmas of all non-punctuation tokens
# Return as a list of lowercase lemmas

text = "The dogs were barking loudly at the cats who were climbing the trees."

doc = nlp(text)

lemmas = [token.lemma_.lower() for token in doc if not token.is_punct]

print("Lemmas:", lemmas)

assert lemmas == ['the', 'dog', 'be', 'bark', 'loudly', 'at', 'the', 'cat', 'who', 'be', 'climb', 'the', 'tree'], "Check your lemmatization!"

"""Part 3: Stop Words and Special Characters

# TODO: Exercise 3.1
"""

from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

# Remove stop words from the following text and return the remaining tokens
# Make sure to lowercase the text first!

text = "This is a sample sentence showing the removal of stop words from the text"

# Step 1: Lowercase and tokenize
tokens = word_tokenize(text.lower())

# Get English stop words
stop_words_nltk = set(stopwords.words('english'))

# Step 2: Remove stop words
filtered = [token for token in tokens if token not in stop_words_nltk]

print("Filtered tokens:", filtered)

assert filtered == ['sample', 'sentence', 'showing', 'removal', 'stop', 'words', 'text'], "Check your filtering!"

"""# TODO: Exercise 3.2"""

import re

text = "Check out @OpenAI's new model! https://openai.com #AI #MachineLearning It's amazing!!!"

clean = text

# Remove URLs
clean = re.sub(r"http\S+", "", clean)

# Remove mentions, including any possessive 's
clean = re.sub(r"@\w+'?s?", "", clean)

# Remove hashtags
clean = re.sub(r"#\w+", "", clean)

# Remove punctuation
clean = re.sub(r"[^\w\s]", "", clean)

# Lowercase
clean = clean.lower()

# Remove extra whitespace
clean = re.sub(r"\s+", " ", clean).strip()

print(f"Clean text: '{clean}'")

assert clean == "check out new model its amazing", f"Got: '{clean}'"

"""Part 4: Complete Preprocessing Pipeline

# TODO: Exercise 4.1 (FINAL CHALLENGE)
"""

import re
import spacy
from nltk.corpus import stopwords

# Load spaCy model once
nlp = spacy.load("en_core_web_sm")

# Create stop words set once
stop_words = set(stopwords.words("english"))

def preprocess_text(text):
    """
    Complete text preprocessing pipeline.

    Args:
        text (str): Raw input text

    Returns:
        list: List of preprocessed tokens
    """

    # Step 1: Lowercase
    text = text.lower()

    # Step 2: Remove URLs
    text = re.sub(r'https?://\S+|www\.\S+', '', text)

    # Step 3: Remove emails
    text = re.sub(r'\b[\w\.-]+?@\w+?\.\w+?\b', '', text)

    # Step 4: Remove mentions and hashtags
    text = re.sub(r'@\w+', '', text)
    text = re.sub(r'#\w+', '', text)

    # Step 5: Remove numbers
    text = re.sub(r'\d+', '', text)

    # Step 6: Remove punctuation/special characters
    text = re.sub(r'[^a-z\s]', ' ', text)

    # Clean extra spaces before tokenization
    text = re.sub(r'\s+', ' ', text).strip()

    # Step 7: Tokenize (use spaCy)
    doc = nlp(text)

    # Step 8 & 9: Remove stop words and lemmatize
    tokens = [
        token.lemma_
        for token in doc
        if token.text not in stop_words and not token.is_space
    ]

    # Step 10: Remove short tokens
    tokens = [token for token in tokens if len(token) >= 2]

    return tokens

"""*Pipline Test*"""

# Test your pipeline with this text
test_text = """
🚀 BREAKING NEWS!!! The researchers at @MIT have published 5 new papers
about Natural Language Processing! Check out https://mit.edu/nlp for details.
Contact them at research@mit.edu for collaborations. #NLP #AI #Research

The experiments were conducted using state-of-the-art transformers models.
They achieved 95.5% accuracy on the benchmark datasets!!!
"""

result = preprocess_text(test_text)
print("Preprocessed tokens:")
print(result)

# Verify some expected tokens are in the result
expected_tokens = ['researcher', 'publish', 'paper', 'natural', 'language', 'processing']
for token in expected_tokens:
    assert token in result, f"Expected '{token}' in result"

# Verify unwanted elements are NOT in result
unwanted = ['@mit', 'https', 'mit.edu', '#nlp', '95.5', '!!!', 'the', 'a', 'at']
for item in unwanted:
    assert item not in result, f"'{item}' should not be in result"

print("\n✅ All tests passed!")

"""# TODO: Exercise 4.2"""

# Apply your preprocessing pipeline to a list of documents
# Return a list of lists (one list of tokens per document)

documents = [
    "Machine learning is transforming the tech industry! @Google #ML",
    "I love programming in Python. It's so easy to learn! https://python.org",
    "The cats are sleeping on the couch. They're so lazy!",
    "Contact support@company.com for any questions about our AI products."
]

# Apply your pipeline to each document
processed_docs = [preprocess_text(doc) for doc in documents]

print("Processed documents:")
for i, doc in enumerate(processed_docs):
    print(f"  Doc {i+1}: {doc}")